apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
  - secretName: expenseemailsender
    type: Opaque
    data:
    - objectName: AzureWebJobsStorage
      key: AzureWebJobsStorage
    - objectName: SENDGRID_API_KEY
      key: SENDGRID_API_KEY
    - objectName: FUNCTIONS_WORKER_RUNTIME
      key: FUNCTIONS_WORKER_RUNTIME
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "<Keyvault Name>"
    objects: |
      array:
        - |
          objectName: storageconn
          objectType: secret
          objectAlias: AzureWebJobsStorage
        - |
          objectName: funcruntime
          objectType: secret
          objectAlias: FUNCTIONS_WORKER_RUNTIME
        - |
          objectName: sendgridapi
          objectType: secret
          objectAlias: SENDGRID_API_KEY
    tenantId: "<Tenant ID>"
    resourceGroup: "<Cluster RG Name>"
    subscriptionId: "<Subscription ID>"