apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
    aadpodidbinding: exppoidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        aadpodidbinding: exppoidentity
    spec:
      containers:
      - name: backend
        image: cncfazure.azurecr.io/conexp/api:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: KeyVaultName
          value: "expensesvault"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
