apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseemailsender
  namespace: default
  labels:
    app: expenseemailsender
    aadpodidbinding: <identity name created>
spec:
  selector:
    matchLabels:
      app: expenseemailsender
  template:
    metadata:
      labels:
        app: expenseemailsender
        aadpodidbinding: <identity name created>
    spec:
      containers:
      - name: expenseemailsender
        image: <function image built>
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: ExpenseEmailSender
        envFrom:
        - secretRef:
            name: expenseemailsender
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: expenseemailsender
  namespace: default
  labels:
    deploymentName: expenseemailsender
spec:
  scaleTargetRef:
    name: expenseemailsender
  triggers:
  - type: azure-queue
    metadata:
      type: queueTrigger
      connectionFromEnv: AzureWebJobsStorage
      queueName: contosoexpenses
---

