data:
  AzureWebJobsStorage: __STORAGECONN64__
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
  SENDGRID_API_KEY: __SENDGRID__
apiVersion: v1
kind: Secret
metadata:
  name: expenseemailsender
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseemailsender
  namespace: default
  labels:
    app: expenseemailsender
spec:
  selector:
    matchLabels:
      app: expenseemailsender
  template:
    metadata:
      labels:
        app: expenseemailsender
    spec:
      containers:
      - name: expenseemailsender
        image: __FUNCIMAGE__
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: ExpenseEmailSender
        envFrom:
        - secretRef:
            name: expenseemailsender
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: expenseemailsender
  namespace: default
  labels:
    deploymentName: expenseemailsender
spec:
  scaleTargetRef:
    name: expenseemailsender
  triggers:
  - type: azure-queue
    metadata:
      type: queueTrigger
      connectionFromEnv: AzureWebJobsStorage
      queueName: contosoexpenses
---

