on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Build and push image'
          run: |
            sed -i 's/__DBAPICONN__/${{ steps.expGetSecretAction.outputs.mysqlconnapi }}/g' yml/backend.yaml
            
            cat yml/backend.yaml