on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Get Secrets for Azure Keyvault'
          uses: Azure/get-keyvault-secrets@v1.0
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          with:
            keyvault: "expensesvault"
            secrets: 'mysqlconnapi, mysqlconnweb, sendgridapi, storageconn'
          id: expGetSecretAction

        - name: 'Docker Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Build and push image'
          run: |
            cd source/Contoso.Expenses.API
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/api:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/api:${{ github.sha }}

            cd ..
            docker build . -f Contoso.Expenses.Web/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/web:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/web:${{ github.sha }}

            docker build . -f Contoso.Expenses.KedaFunctions/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/emaildispatcher:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/emaildispatcher:${{ github.sha }}

            cd ..
            sed -i "s/__APIIMAGE__/${{ secrets.REGISTRY_LOGIN_SERVER }}/conexp/api:${{ github.sha }}/g" yml/backend.yaml
            sed -i "s/__DBAPICONN__/${{ steps.expGetSecretAction.outputs.mysqlconnapi }}/g" yml/backend.yaml
            
            cat yml/backend.yaml